name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.2
- flask=3.0.0
- numpy=1.26.0
- xgboost=1.7.3
- matplotlib=3.8.0
- ipython
- lightgbm
- pytest
- flask-testing