name: Docker Build and Pytest

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Build Docker container
      run: docker build -t app .

    - name: UnitTest with pytest
      run: |
        docker-compose up -d
        docker-compose exec -T app pytest
